#!/usr/bin/env bash
# Credits: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/Desktop/4ano/2Semestre/ ~/Desktop/RandomCode/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -d -s "$selected_name" -c "$selected"
    tmux rename-window -t "$selected_name":1 "nvim"
    tmux send-keys -t "$selected_name":1 "nvim" C-m
    tmux new-window -t "$selected_name":2 -c "$selected" -n "main"
    tmux send-keys -t "$selected_name":2 "l" C-m
    tmux attach -t "$selected_name"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
    tmux rename-window -t "$selected_name":1 "nvim"
    tmux send-keys -t "$selected_name":1 "nvim" C-m
    tmux new-window -t "$selected_name":2 -c "$selected" -n "main"
    tmux send-keys -t "$selected_name":2 "l" C-m
fi

tmux attach -t "$selected_name"
