#!/usr/bin/env bash

# Wait for a window with a given app name in a given workspace
wait_for_window_in_workspace() {
    app_name="$1"
    workspace="$2"
    while true; do
        if aerospace list-windows --workspace "$workspace" | grep "$app_name" >/dev/null; then
            sleep 0.5
            break
        fi
        sleep 0.1
    done
}

# --- Workspace 1: WezTerm ---
aerospace msg workspace 1
open -n "/Applications/WezTerm.app"
sleep 4
aerospace move-node-to-workspace 1
wait_for_window_in_workspace "WezTerm" 1
wezterm cli spawn -- bash -c "tmux"
sleep 3

# --- Workspace 2: Zen ---
open -n "/Applications/Zen.app"
sleep 4
aerospace move-node-to-workspace 2
wait_for_window_in_workspace "Zen" 2

# --- Workspace 3: Microsoft Teams + Todoist ---
open -n "/Applications/Microsoft Teams.app"
sleep 10
aerospace move-node-to-workspace 3
wait_for_window_in_workspace "Microsoft Teams" 3
open -n "/Applications/Todoist.app"
sleep 4
aerospace move-node-to-workspace 3
wait_for_window_in_workspace "Todoist" 3

# --- Workspace 4: Obsidian ---
open -n "/Applications/Obsidian.app"
sleep 3
aerospace move-node-to-workspace 4
wait_for_window_in_workspace "Obsidian" 4

# --- Workspace 5: Utils ---
nohup /Applications/AWS\ VPN\ Client/AWS\ VPN\ Client.app/Contents/MacOS/AWS\ VPN\ Client 2>&1 &
sleep 3
open "/Applications/flameshot.app"
sleep 2

# --- Workspace 8: Outlook ---
open -n "/Applications/Microsoft Outlook.app"
sleep 10
aerospace move-node-to-workspace 8
wait_for_window_in_workspace "Microsoft Outlook" 8

# --- Workspace 9: YT Music ---
open -n "/Applications/YT Music.app"
sleep 4
aerospace move-node-to-workspace 9
wait_for_window_in_workspace "YT Music" 9

# --- Workspace 10: Brave ---
open -n "/Applications/Brave Browser.app"
sleep 4
aerospace move-node-to-workspace 10
